/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VozRouteImport } from './routes/voz'
import { Route as TextoRouteImport } from './routes/texto'
import { Route as MentoresRouteImport } from './routes/mentores'
import { Route as FotoRouteImport } from './routes/foto'
import { Route as IndexRouteImport } from './routes/index'

const VozRoute = VozRouteImport.update({
  id: '/voz',
  path: '/voz',
  getParentRoute: () => rootRouteImport,
} as any)
const TextoRoute = TextoRouteImport.update({
  id: '/texto',
  path: '/texto',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoresRoute = MentoresRouteImport.update({
  id: '/mentores',
  path: '/mentores',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoRoute = FotoRouteImport.update({
  id: '/foto',
  path: '/foto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foto': typeof FotoRoute
  '/mentores': typeof MentoresRoute
  '/texto': typeof TextoRoute
  '/voz': typeof VozRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foto': typeof FotoRoute
  '/mentores': typeof MentoresRoute
  '/texto': typeof TextoRoute
  '/voz': typeof VozRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foto': typeof FotoRoute
  '/mentores': typeof MentoresRoute
  '/texto': typeof TextoRoute
  '/voz': typeof VozRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/foto' | '/mentores' | '/texto' | '/voz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/foto' | '/mentores' | '/texto' | '/voz'
  id: '__root__' | '/' | '/foto' | '/mentores' | '/texto' | '/voz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FotoRoute: typeof FotoRoute
  MentoresRoute: typeof MentoresRoute
  TextoRoute: typeof TextoRoute
  VozRoute: typeof VozRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voz': {
      id: '/voz'
      path: '/voz'
      fullPath: '/voz'
      preLoaderRoute: typeof VozRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texto': {
      id: '/texto'
      path: '/texto'
      fullPath: '/texto'
      preLoaderRoute: typeof TextoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentores': {
      id: '/mentores'
      path: '/mentores'
      fullPath: '/mentores'
      preLoaderRoute: typeof MentoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto': {
      id: '/foto'
      path: '/foto'
      fullPath: '/foto'
      preLoaderRoute: typeof FotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FotoRoute: FotoRoute,
  MentoresRoute: MentoresRoute,
  TextoRoute: TextoRoute,
  VozRoute: VozRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
