CREATE TABLE Sheet1(--_============================================================ VARCHAR(10));
INSERT INTO Sheet1 (--_============================================================) VALUES 
('-- BANCO DE DADOS COMPLETO'),
('-- Aplicativo de Mentoria e Alfabetização Tecnológica'),
('-- para Escolas Públicas'),
('-- SGBD: PostgreSQL 15+'),
('-- Versão: 2.0 — Integrado com Foto, Áudio e IA'),
('-- ============================================================'),
('-- ============================================================'),
('-- TIPOS ENUM'),
('-- ============================================================'),
('CREATE TYPE tipo_perfil_enum  AS ENUM ('aluno', 'mentor', 'admin');'),
('CREATE TYPE status_mentoria   AS ENUM ('pendente', 'aceita', 'rejeitada', 'concluida');'),
('CREATE TYPE status_conteudo   AS ENUM ('ativo', 'inativo', 'rascunho');'),
('CREATE TYPE tipo_conteudo     AS ENUM ('video', 'texto', 'quiz', 'exercicio');'),
('CREATE TYPE nivel_dificuldade AS ENUM ('iniciante', 'intermediario', 'avancado');'),
('CREATE TYPE tipo_midia_enum   AS ENUM ('texto', 'foto', 'audio'); -- NOVO v2.0'),
('CREATE TYPE status_arquivo    AS ENUM ('processando', 'pronto', 'erro');  -- NOVO v2.0'),
('-- ============================================================'),
('-- 1. USUARIO'),
('-- Alunos, mentores e administradores.'),
('-- Consentimento de responsável obrigatório (LGPD — Art. 14).'),
('-- UC: Realiza Cadastro, Fazer Login, Edita Perfil'),
('-- ============================================================'),
('CREATE TABLE usuario ('),
('    id                  UUID             PRIMARY KEY DEFAULT gen_random_uuid(),'),
('    nome                VARCHAR(150)     NOT NULL,'),
('    email               VARCHAR(254)     NOT NULL UNIQUE,'),
('    senha_hash          VARCHAR(255)     NOT NULL,       -- bcrypt / argon2'),
('    tipo_perfil         tipo_perfil_enum NOT NULL,'),
('    data_nascimento     DATE             NOT NULL,'),
('    foto_url            TEXT,'),
('    bio                 TEXT,'),
('    nivel               INTEGER          NOT NULL DEFAULT 1  CHECK (nivel >= 1),'),
('    xp_total            INTEGER          NOT NULL DEFAULT 0  CHECK (xp_total >= 0),'),
('    ativo               BOOLEAN          NOT NULL DEFAULT TRUE,'),
('    consentimento_resp  BOOLEAN          NOT NULL DEFAULT FALSE,  -- LGPD menores'),
('    email_verificado    BOOLEAN          NOT NULL DEFAULT FALSE,'),
('    criado_em           TIMESTAMPTZ      NOT NULL DEFAULT NOW(),'),
('    atualizado_em       TIMESTAMPTZ      NOT NULL DEFAULT NOW()'),
(');'),
('COMMENT ON TABLE  usuario IS 'Usuários: alunos, mentores e administradores.';'),
('COMMENT ON COLUMN usuario.senha_hash        IS 'Hash bcrypt/Argon2. Nunca texto puro.';'),
('COMMENT ON COLUMN usuario.consentimento_resp IS 'Consentimento do responsável (LGPD Art.14 — menores de 18).';'),
('COMMENT ON COLUMN usuario.xp_total          IS 'XP acumulado para gamificação.';'),
('-- ============================================================'),
('-- 2. AREA_INTERESSE'),
('-- Áreas para match aluno ↔ mentor'),
('-- UC: Solicita a Mentoria / Realiza Match com Mentor'),
('-- ============================================================'),
('CREATE TABLE area_interesse ('),
('    id   UUID         PRIMARY KEY DEFAULT gen_random_uuid(),'),
('    nome VARCHAR(100) NOT NULL UNIQUE'),
(');'),
('INSERT INTO area_interesse (nome) VALUES'),
('    ('Celular e Smartphone'),'),
('    ('Computador e Notebook'),'),
('    ('Internet e Wi-Fi'),'),
('    ('E-mail e Redes Sociais'),'),
('    ('Lógica de Programação'),'),
('    ('Python'),'),
('    ('Web Development'),'),
('    ('Design Digital'),'),
('    ('Robótica'),'),
('    ('Inteligência Artificial'),'),
('    ('Banco de Dados'),'),
('    ('Redes de Computadores');'),
('-- ============================================================'),
('-- 3. USUARIO_AREA — N:N'),
('-- UC: Edita Perfil / Realiza Match com Mentor'),
('-- ============================================================'),
('CREATE TABLE usuario_area ('),
('    usuario_id UUID NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,'),
('    area_id    UUID NOT NULL REFERENCES area_interesse(id) ON DELETE CASCADE,'),
('    PRIMARY KEY (usuario_id, area_id)'),
(');'),
('-- ============================================================'),
('-- 4. TRILHA'),
('-- Trilhas de aprendizado gamificadas'),
('-- UC: Acessa Trilha de Aprendizado / Gerencia Trilhas e Conteúdos'),
('-- ============================================================'),
('CREATE TABLE trilha ('),
('    id            UUID             PRIMARY KEY DEFAULT gen_random_uuid(),'),
('    titulo        VARCHAR(200)     NOT NULL,'),
('    descricao     TEXT,'),
('    nivel         nivel_dificuldade NOT NULL DEFAULT 'iniciante','),
('    imagem_url    TEXT,'),
('    status        status_conteudo  NOT NULL DEFAULT 'ativo','),
('    criado_por    UUID             NOT NULL REFERENCES usuario(id),'),
('    criado_em     TIMESTAMPTZ      NOT NULL DEFAULT NOW(),'),
('    atualizado_em TIMESTAMPTZ      NOT NULL DEFAULT NOW()'),
(');'),
('-- ============================================================'),
('-- 5. MODULO'),
('-- Módulo dentro de uma trilha (com XP)'),
('-- UC: Realiza Atividades (include de Acessa Trilha)'),
('-- ============================================================'),
('CREATE TABLE modulo ('),
('    id        UUID            PRIMARY KEY DEFAULT gen_random_uuid(),'),
('    trilha_id UUID            NOT NULL REFERENCES trilha(id) ON DELETE CASCADE,'),
('    titulo    VARCHAR(200)    NOT NULL,'),
('    descricao TEXT,'),
('    ordem     INTEGER         NOT NULL DEFAULT 1 CHECK (ordem >= 1),'),
('    pontos_xp INTEGER         NOT NULL DEFAULT 10 CHECK (pontos_xp >= 0),'),
('    status    status_conteudo NOT NULL DEFAULT 'ativo','),
('    criado_em TIMESTAMPTZ     NOT NULL DEFAULT NOW()'),
(');'),
('-- ============================================================'),
('-- 6. CONTEUDO'),
('-- Materiais de um módulo (vídeo, texto, quiz, exercício)'),
('-- UC: Realiza Atividades'),
('-- ============================================================'),
('CREATE TABLE conteudo ('),
('    id          UUID            PRIMARY KEY DEFAULT gen_random_uuid(),'),
('    modulo_id   UUID            NOT NULL REFERENCES modulo(id) ON DELETE CASCADE,'),
('    titulo      VARCHAR(200)    NOT NULL,'),
('    tipo        tipo_conteudo   NOT NULL,'),
('    url_recurso TEXT,'),
('    texto_corpo TEXT,'),
('    ordem       INTEGER         NOT NULL DEFAULT 1,'),
('    status      status_conteudo NOT NULL DEFAULT 'ativo','),
('    criado_em   TIMESTAMPTZ     NOT NULL DEFAULT NOW()'),
(');'),
('-- ============================================================'),
('-- 7. PROGRESSO'),
('-- Conclusão de módulos + XP do aluno (gamificação)'),
('-- UC: Acessa Trilha de Aprendizado → Realiza Atividades'),
('-- ============================================================'),
('CREATE TABLE progresso ('),
('    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),'),
('    aluno_id       UUID        NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,'),
('    modulo_id      UUID        NOT NULL REFERENCES modulo(id) ON DELETE CASCADE,'),
('    data_conclusao TIMESTAMPTZ NOT NULL DEFAULT NOW(),'),
('    pontuacao      INTEGER     DEFAULT 0 CHECK (pontuacao >= 0),'),
('    UNIQUE (aluno_id, modulo_id)'),
(');'),
('COMMENT ON TABLE progresso IS 'Registro de módulos concluídos. UNIQUE evita dupla contagem de XP.';'),
('-- ============================================================'),
('-- 8. MENTORIA'),
('-- Vínculo aluno ↔ mentor com ciclo de vida completo'),
('-- UC: Solicita a Mentoria → Realiza Match → Recebe Solicitação'),
('--     → Aceita ou Rejeita → Acompanha Alunos Mentorados'),
('-- ============================================================'),
('CREATE TABLE mentoria ('),
('    id                   UUID           PRIMARY KEY DEFAULT gen_random_uuid(),'),
('    aluno_id             UUID           NOT NULL REFERENCES usuario(id),'),
('    mentor_id            UUID           NOT NULL REFERENCES usuario(id),'),
('    status               status_mentoria NOT NULL DEFAULT 'pendente','),
('    mensagem_solicitacao TEXT,'),
('    data_solicitacao     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),'),
('    data_resposta        TIMESTAMPTZ,'),
('    data_conclusao       TIMESTAMPTZ,'),
('    CONSTRAINT ck_aluno_ne_mentor CHECK (aluno_id <> mentor_id)'),
(');'),
('COMMENT ON COLUMN mentoria.status IS 'Ciclo: pendente → aceita/rejeitada → concluida.';'),
('-- ============================================================'),
('-- 9. ARQUIVO_MIDIA                        *** NOVO v2.0 ***'),
('-- Armazena fotos e áudios enviados pelo usuário para a IA'),
('-- UC: Realiza Perguntas para IA (via foto ou áudio)'),
('-- ============================================================'),
('CREATE TABLE arquivo_midia ('),
('    id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),'),
('    usuario_id      UUID          NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,'),
('    tipo            tipo_midia_enum NOT NULL,          -- 'foto' | 'audio' | 'texto''),
('    url_storage     TEXT,                              -- URL no bucket (S3/Supabase Storage)'),
('    nome_original   VARCHAR(255),                     -- nome do arquivo original'),
('    tamanho_bytes   INTEGER,                           -- tamanho em bytes'),
('    mime_type       VARCHAR(100),                      -- image/jpeg, audio/mp3, etc.'),
('    transcricao     TEXT,                              -- para áudio: texto transcrito'),
('    status          status_arquivo NOT NULL DEFAULT 'processando','),
('    criado_em       TIMESTAMPTZ    NOT NULL DEFAULT NOW()'),
(');'),
('COMMENT ON TABLE arquivo_midia IS 'Fotos e áudios enviados pelo usuário ao assistente de IA.';'),
('COMMENT ON COLUMN arquivo_midia.transcricao IS 'Transcrição automática do áudio (Speech-to-Text).';'),
('COMMENT ON COLUMN arquivo_midia.url_storage IS 'URL do arquivo no Supabase Storage ou S3.';'),
('-- ============================================================'),
('-- 10. IA_INTERACAO                        *** ATUALIZADO v2.0 ***'),
('-- Log de todas as interações com a IA (texto, foto, áudio)'),
('-- UC: Realiza Perguntas para IA'),
('--     IA (Sistema Externo): Responde Dúvidas Automaticamente'),
('-- ============================================================'),
('CREATE TABLE ia_interacao ('),
('    id             UUID            PRIMARY KEY DEFAULT gen_random_uuid(),'),
('    usuario_id     UUID            NOT NULL REFERENCES usuario(id),'),
('    arquivo_id     UUID            REFERENCES arquivo_midia(id),  -- FK → foto ou áudio (nullable)'),
('    tipo_midia     tipo_midia_enum NOT NULL DEFAULT 'texto',       -- como o usuário perguntou'),
('    pergunta       TEXT            NOT NULL,                       -- texto da pergunta'),
('    resposta_ia    TEXT            NOT NULL,                       -- resposta gerada pela IA'),
('    contexto       TEXT,                                           -- módulo, trilha, etc.'),
('    tokens_usados  INTEGER,'),
('    modelo_ia      VARCHAR(100)    DEFAULT 'claude-sonnet-4',      -- qual modelo respondeu'),
('    avaliacao      SMALLINT        CHECK (avaliacao BETWEEN 1 AND 5), -- rating do usuário'),
('    criado_em      TIMESTAMPTZ     NOT NULL DEFAULT NOW()'),
(');'),
('COMMENT ON TABLE ia_interacao IS 'Log de interações com IA por texto, foto ou áudio.';'),
('COMMENT ON COLUMN ia_interacao.arquivo_id   IS 'FK opcional para arquivo_midia — presente quando a pergunta vem via foto ou áudio.';'),
('COMMENT ON COLUMN ia_interacao.tipo_midia   IS 'texto = digitou; foto = enviou imagem; audio = gravou voz.';'),
('COMMENT ON COLUMN ia_interacao.avaliacao    IS '1-5 estrelas dadas pelo usuário após a resposta.';'),
('-- ============================================================'),
('-- 11. FORUM_POST'),
('-- Perguntas públicas no fórum'),
('-- UC: Participa do Forum de Duvidas / Modera Fórum e Dúvidas'),
('-- ============================================================'),
('CREATE TABLE forum_post ('),
('    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),'),
('    autor_id      UUID        NOT NULL REFERENCES usuario(id),'),
('    titulo        VARCHAR(300) NOT NULL,'),
('    corpo         TEXT        NOT NULL,'),
('    arquivo_id    UUID        REFERENCES arquivo_midia(id),  -- foto/áudio na pergunta'),
('    resolvido     BOOLEAN     NOT NULL DEFAULT FALSE,'),
('    criado_em     TIMESTAMPTZ NOT NULL DEFAULT NOW(),'),
('    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()'),
(');'),
('COMMENT ON COLUMN forum_post.arquivo_id IS 'Opcional: foto ou áudio anexado à pergunta do fórum.';'),
('-- ============================================================'),
('-- 12. FORUM_RESPOSTA'),
('-- Respostas humanas ou geradas pela IA no fórum'),
('-- UC: Responde Perguntas do Forum de Duvidas'),
('--     IA: Responde Dúvidas Automaticamente'),
('-- ============================================================'),
('CREATE TABLE forum_resposta ('),
('    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),'),
('    post_id          UUID        NOT NULL REFERENCES forum_post(id) ON DELETE CASCADE,'),
('    autor_id         UUID        NOT NULL REFERENCES usuario(id),'),
('    corpo            TEXT        NOT NULL,'),
('    respondido_por_ia BOOLEAN    NOT NULL DEFAULT FALSE,'),
('    criado_em        TIMESTAMPTZ NOT NULL DEFAULT NOW()'),
(');'),
('-- ============================================================'),
('-- 13. NOTIFICACAO'),
('-- Alertas in-app (mentoria aceita, módulo concluído, etc.)'),
('-- UC: todos que geram eventos para o usuário'),
('-- ============================================================'),
('CREATE TABLE notificacao ('),
('    id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),'),
('    usuario_id UUID         NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,'),
('    titulo     VARCHAR(200) NOT NULL,'),
('    corpo      TEXT,'),
('    lida       BOOLEAN      NOT NULL DEFAULT FALSE,'),
('    criado_em  TIMESTAMPTZ  NOT NULL DEFAULT NOW()'),
(');'),
('-- ============================================================'),
('-- ÍNDICES DE PERFORMANCE'),
('-- ============================================================'),
('CREATE INDEX idx_usuario_tipo         ON usuario(tipo_perfil);'),
('CREATE INDEX idx_usuario_ativo        ON usuario(ativo);'),
('CREATE INDEX idx_progresso_aluno      ON progresso(aluno_id);'),
('CREATE INDEX idx_progresso_modulo     ON progresso(modulo_id);'),
('CREATE INDEX idx_progresso_data       ON progresso(data_conclusao);'),
('CREATE INDEX idx_mentoria_aluno       ON mentoria(aluno_id);'),
('CREATE INDEX idx_mentoria_mentor      ON mentoria(mentor_id);'),
('CREATE INDEX idx_mentoria_status      ON mentoria(status);'),
('CREATE INDEX idx_arquivo_usuario      ON arquivo_midia(usuario_id);'),
('CREATE INDEX idx_arquivo_tipo         ON arquivo_midia(tipo);'),
('CREATE INDEX idx_ia_usuario           ON ia_interacao(usuario_id);'),
('CREATE INDEX idx_ia_tipo              ON ia_interacao(tipo_midia);'),
('CREATE INDEX idx_ia_criado            ON ia_interacao(criado_em DESC);'),
('CREATE INDEX idx_forum_autor          ON forum_post(autor_id);'),
('CREATE INDEX idx_forum_resp_post      ON forum_resposta(post_id);'),
('CREATE INDEX idx_notif_usuario        ON notificacao(usuario_id, lida);'),
('-- ============================================================'),
('-- VIEW 1: Ranking semanal de XP (gamificação)'),
('-- UC: Dashboard do Aluno — Visualiza Progresso'),
('-- ============================================================'),
('CREATE OR REPLACE VIEW vw_ranking_semanal AS'),
('SELECT'),
('    u.id,'),
('    u.nome,'),
('    u.foto_url,'),
('    u.nivel,'),
('    COALESCE(SUM(m.pontos_xp) FILTER ('),
('        WHERE p.data_conclusao >= date_trunc('week', NOW())'),
('    ), 0)                                AS xp_semana,'),
('    u.xp_total,'),
('    RANK() OVER (ORDER BY'),
('        COALESCE(SUM(m.pontos_xp) FILTER ('),
('            WHERE p.data_conclusao >= date_trunc('week', NOW())'),
('        ), 0) DESC'),
('    )                                    AS posicao'),
('FROM usuario u'),
('LEFT JOIN progresso p ON p.aluno_id = u.id'),
('LEFT JOIN modulo m    ON m.id = p.modulo_id'),
('WHERE u.tipo_perfil = 'aluno''),
('  AND u.ativo = TRUE'),
('GROUP BY u.id, u.nome, u.foto_url, u.nivel, u.xp_total;'),
('-- ============================================================'),
('-- VIEW 2: Dashboard do mentor (alunos + progresso)'),
('-- UC: Acompanha Alunos Mentorados'),
('-- ============================================================'),
('CREATE OR REPLACE VIEW vw_dashboard_mentor AS'),
('SELECT'),
('    me.mentor_id,'),
('    me.aluno_id,'),
('    u.nome          AS nome_aluno,'),
('    u.nivel,'),
('    u.xp_total,'),
('    me.status       AS status_mentoria,'),
('    me.data_solicitacao,'),
('    COUNT(p.id)     AS modulos_concluidos'),
('FROM mentoria me'),
('JOIN  usuario u     ON u.id  = me.aluno_id'),
('LEFT JOIN progresso p ON p.aluno_id = me.aluno_id'),
('WHERE me.status = 'aceita''),
('GROUP BY me.mentor_id, me.aluno_id, u.nome, u.nivel,'),
('         u.xp_total, me.status, me.data_solicitacao;'),
('-- ============================================================'),
('-- VIEW 3: Estatísticas de uso da IA por tipo de mídia'),
('-- UC: Visualiza Relatórios e Métricas (Admin)'),
('-- ============================================================'),
('CREATE OR REPLACE VIEW vw_uso_ia AS'),
('SELECT'),
('    tipo_midia,'),
('    COUNT(*)                          AS total_interacoes,'),
('    ROUND(AVG(avaliacao)::NUMERIC, 2) AS avaliacao_media,'),
('    SUM(tokens_usados)                AS tokens_totais,'),
('    date_trunc('day', criado_em)      AS dia'),
('FROM ia_interacao'),
('GROUP BY tipo_midia, date_trunc('day', criado_em)'),
('ORDER BY dia DESC;'),
('-- ============================================================'),
('-- VIEW 4: Perguntas via foto ou áudio (para auditoria IA)'),
('-- UC: IA (Sistema Externo) — Responde Dúvidas'),
('-- ============================================================'),
('CREATE OR REPLACE VIEW vw_interacoes_midia AS'),
('SELECT'),
('    i.id,'),
('    u.nome         AS usuario_nome,'),
('    u.tipo_perfil,'),
('    i.tipo_midia,'),
('    a.url_storage  AS arquivo_url,'),
('    a.transcricao  AS audio_transcrito,'),
('    i.pergunta,'),
('    i.resposta_ia,'),
('    i.avaliacao,'),
('    i.criado_em'),
('FROM ia_interacao i'),
('JOIN usuario u      ON u.id = i.usuario_id'),
('LEFT JOIN arquivo_midia a ON a.id = i.arquivo_id'),
('WHERE i.tipo_midia IN ('foto', 'audio')'),
('ORDER BY i.criado_em DESC;');